version: '3.7'

x-common-variables: &common-variables
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  INSTALLED_APPS: ${INSTALLED_APPS}
  CORS_MIDDLEWARE: ${CORS_MIDDLEWARE}
  STATIC_URL: ${STATIC_URL}
  SOCIAL_AUTH_AGOL_DOMAIN: ${SOCIAL_AUTH_AGOL_DOMAIN}
  SOCIAL_AUTH_AGOL_KEY: ${SOCIAL_AUTH_AGOL_KEY}
  SOCIAL_AUTH_AGOL_SECRET: ${SOCIAL_AUTH_AGOL_SECRET}
  SOCIAL_AUTH_REDIRECT_IS_HTTPS: ${SOCIAL_AUTH_REDIRECT_IS_HTTPS}
  SOCIAL_AUTH_PIPELINE: ${SOCIAL_AUTH_PIPELINE}
  SOCIAL_AUTH_AGOL_PREAPPROVED_DOMAINS: ${SOCIAL_AUTH_AGOL_PREAPPROVED_DOMAINS}
  SOCIAL_AUTH_AGOL_UNKNOWN_REQUESTER_GROUP_ID: ${SOCIAL_AUTH_AGOL_UNKNOWN_REQUESTER_GROUP_ID}
  SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: ${SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS}
  REST_FRAMEWORK: ${REST_FRAMEWORK}
  DRF_RECAPTCHA_SECRET_KEY: ${DRF_RECAPTCHA_SECRET_KEY}
  CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST}
  CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
  SENDGRID_API_KEY: ${SENDGRID_API_KEY}
  SENDGRID_SANDBOX_MODE_IN_DEBUG: ${SENDGRID_SANDBOX_MODE_IN_DEBUG}
  SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  SLACK_CHANNEL: ${SLACK_CHANNEL}
  USE_X_FORWARDED_HOST: ${USE_X_FORWARDED_HOST}
  URL_PREFIX: ${URL_PREFIX}
  INTERNAL_IPS: ${INTERNAL_IPS}
  HOST_ADDRESS: ${HOST_ADDRESS}
  COORDINATOR_ADMIN_GROUP_ID: ${COORDINATOR_ADMIN_GROUP_ID}

services:

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    image: docker.itgis.innovateteam.com/request_api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEBUG: ${DEBUG}
