version: '3.7'

services:
  db:
    ports:
      - "1434:1433"
    volumes:
      - ../mssqldata:/var/opt/mssql/data
      - ../mssqlbackup:/var/opt/mssql/backups
  api:
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
