version: '3.7'

services:
  db:
    volumes:
      - requesttool_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  requesttool_db: