
services:
  request_api:
    command: /bin/sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 AGOLAccountRequestor.wsgi"
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.scope=innovate"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: tbock@innovateteam.com
    command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/template.nginx > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    expose:
      - "80"
    depends_on:
      - request_api
    image: docker.itgis.innovateteam.com/request_web
    networks:
      - default
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.scope=innovate"
    restart: unless-stopped

networks:
  proxy:
    name: nginx_proxy_default
    external: true
