FROM python:3.9

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install pip --upgrade

RUN pip install --upgrade -r requirements.txt

COPY . /code/
RUN pip install gunicorn
RUN python manage.py collectstatic --noinput
