
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - requesttool_db14:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  request_api:
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  requesttool_db14:
